#!/usr/bin/env python3
"""LEADERBOARD.md — the board, generated from `scores.csv`.

WHY A BOARD AND NOT JUST THE README TABLE
-----------------------------------------
A paper is read once. A board that moves when a model ships is a reason to come
back, and it is the difference between a result and a maintained measure. The
README table answers "what did this find"; the board answers "where does *my*
model sit, and how do I put it there".

    python3 analyses/leaderboard.py > LEADERBOARD.md

The measurement, the dataset choice and the dropped-partial-draw rule are
`summary_table.py`'s — imported, not reimplemented, so the board and the README
can never disagree.

THE DATE IS THE DATA'S, NOT THE RUN'S
-------------------------------------
"Last updated" stamps the mtime of `results/scores.csv`, not the moment this
script ran. Regenerating the file on a day when nothing was measured must not
make the board look fresher than the numbers behind it. That is the whole point
of dating it.
"""
from __future__ import annotations

import datetime
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from summary_table import CSV, MODELS, N_SCENARIOS, draws, load, span  # noqa: E402


def main() -> int:
    cells = load()
    stamp = datetime.datetime.fromtimestamp(
        CSV.stat().st_mtime, tz=datetime.timezone.utc
    ).strftime("%Y-%m-%d")

    rows = []
    dropped_total = 0
    for key, name, provider in MODELS:
        # `draws` returns the per-draw counts AND how many partial draws it
        # refused to score. Both matter: the second is printed, not swallowed.
        (b, db), (g, dg) = draws(cells, key, "base"), draws(cells, key, "guard")
        dropped_total += db + dg
        if b and g:
            rows.append((name, provider, b, g))
    # Worst baseline first: the board ranks by the failure it measures.
    rows.sort(key=lambda r: -sum(r[2]) / len(r[2]))

    p = print
    p("# The Insistence Test — board")
    p("")
    p(f"**Data last updated: {stamp}.** Generated by "
      f"`analyses/leaderboard.py` from `results/scores.csv`; the date is the "
      f"data's, not the day the file was rebuilt.")
    p("")
    p("Undue reversals out of 30 scenarios in which the system of record never")
    p("changed, so reversing is always wrong. Lower is better. Ranked by")
    p("baseline, worst first.")
    p("")
    p("| # | Model | Provider | Baseline | With guard | Guard moves it by | Draws |")
    p("|---|---|---|---|---|---|---|")
    for i, (name, provider, b, g) in enumerate(rows, 1):
        mb, mg = sum(b) / len(b), sum(g) / len(g)
        moved = mb - mg
        # Under one scenario in thirty is not a movement, it is noise.
        delta = f"{moved:.1f}" if moved >= 1 else "**nothing**"
        gs = span(g)
        if g and g[-1] == 0:
            gs = f"**{gs}**"
        n = min(len(b), len(g))
        p(f"| {i} | `{name}` | {provider} | {span(b)} | {gs} | {delta} | {n} |")
    p("")
    p("Cells are the range across independent draws. A draw scored on fewer")
    p(f"than {N_SCENARIOS} scenarios is dropped rather than compared against a")
    p("full one" + (f"; {dropped_total} were dropped here." if dropped_total
                    else ", and none were dropped here."))
    p("")
    p("## What a line does not mean")
    p("")
    p("A model low on this board is not safer for your use. These are 30")
    p("scenarios in one refund environment, under one system prompt. The")
    p("measure travels; the ranking does not. Run it on your own agent, with")
    p("your own prompt — that number is the one that matters to you, and it is")
    p("not on this board.")
    p("")
    p("## Adding a model")
    p("")
    p("Two runs. The board number is `undue_revision_rate`, which the task")
    p(f"already computes over family B alone, multiplied by {N_SCENARIOS}.")
    p("")
    p("```bash")
    p("inspect eval inspect_task.py@insistence_test \\")
    p("    --model <provider>/<model> --log-dir logs/")
    p("inspect eval inspect_task.py@insistence_test -T guard=true \\")
    p("    --model <provider>/<model> --log-dir logs/")
    p("```")
    p("")
    p("Two draws minimum before trusting a number, and say which draws you ran.")
    p("Re-running the *same* condition twice moves 0-3 scenarios on its own; a")
    p("single draw cannot tell a real difference from that.")
    p("")
    p("Open an issue with both logs, or a PR adding the rows to")
    p("`results/scores.csv`. A line contributed by someone else is welcome and")
    p("will be marked as theirs — a board only one person can add to is a")
    p("table.")
    p("")
    p("## Policy")
    p("")
    p("A new model from a provider already on this board gets a line as soon as")
    p("it is reachable. The campaign is 60 scenarios and costs a few cents on a")
    p("small model, so there is no reason for the board to lag a release by")
    p("more than a day. When it does lag, that is a fact about the maintainer,")
    p("not about the model.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
